strategyName: BigMom2023
author: Andra Wang
editedDate: 20220726
createdDate: 20230921

params:
    basic:
        # 起始日
        start_date: '2016-01-01'
        # 结束日
        end_date: '2023-07-13'

weightGenerator:
    maxW: 0.1
    window_size: 500
    step_size: 20
    dateNum: 20
    list_objective: ['average_weight', 'min_volatility_cvx']
    rebalance_trigger: True
        
factor_weight:
    groupNum: 5
    date_out: '2023'

test1:
    # 测试因子名称列表
    list_factor: ['alpha_216']
    # 持仓周期列表
    list_hp: [1, 3, 5, 10, 15, 20]
    # 因子参数列表
    list_N: [5, 10, 20, 30, 60, 100]
    # 绩效结果表头
    list_ratios: ['ar_15', 'sr_15', 'mdd_15', 'mar_15', 'to_15', 'ar_24', 'sr_24',
    'mdd_24', 'mar_24', 'to_24','IC_mean', 'ICIR', 'rankIC_mean', 'rankICIR']
    # 是否作图的标识
    bool_test_fig: True 

test:
    # 测试因子名称列表
    list_factor: ['alpha_216']
    # 持仓周期列表
    list_hp: [1, 3, 5, 10, 15, 20]
    # 因子参数列表
    list_N: [5, 10, 20, 30, 60, 100]
    # 绩效结果表头
    list_ratios: ['parameter',
    'ar_15_fee', 'sr_15_fee', 'mdd_15_fee', 'mar_15_fee',
    'ar_24_fee', 'sr_24_fee', 'mdd_24_fee', 'mar_24_fee', 
    'ar_12_fee', 'sr_12_fee', 'mdd_12_fee', 'mar_12_fee',
    'IC_mean', 'ICIR', 'rankIC_mean', 'rankICIR',
    'ar_15', 'sr_15', 'mdd_15', 'mar_15', 'to_15', 
    'ar_24', 'sr_24', 'mdd_24', 'mar_24', 'to_24',
    'ar_12', 'sr_12', 'mdd_12', 'mar_12', 'to_12', 
    'factorName']
    # 是否作图的标识
    bool_test_fig: True 
    # 标准交易费用(估)
    fee: 0.0005


path:
    filepath_index: 'D:/Data/local_data_daily_update/nj_index_dataset.csv'
    
    filepath_future_list: 'D:/Data/future_list.csv'
    
    filepath_mainsub: 'D:/Data/tushare/quote/quote2.csv'
    
    filepath_main: 'D:/Data/tushare/factor/'
    
    filepath_retMainJump: 'D:/Data/tushare/factor/retMainJump.csv'
    
    filepath_factorsF: 'D:/Data/tushare/wts_factors&returns_Funda.h5'
    
    filepath_factorTable2023: 'D:/ProgramFiles/python/strategy_factor/BigMom2023/config/factorTable2023.xlsx'
    
    filepath_factorPools: 'D:/ProgramFiles/python/strategy_factor/BigMom2023/config/factorPools.xlsx'
    
    filepath_output: 'D:/ProgramFiles/python/strategy_factor/BigMom2023/output/'
    
    filepath_cal_date: 'D:/Data/cal_date.csv'
    
    filepath_capital: 'D:/ProgramFiles/python/strategy_factor/BigMom2023/config/BigMom2023_capital.csv'
    
    filepath_templete: 'D:/ProgramFiles/python/strategy_factor/BigMom2023/position_trade/CTA_BigMom.csv'
    
    filepath_tradePosition: 'D:/ProgramFiles/python/strategy_factor/BigMom2023/position_trade/'
    # ## F相关文件   
    # #detail: 'f选取因子的权重'
    # filepath_pick_weight_f: 'output/wight_allocation/weight_pick_F.csv'
    
    # filepath_factorTableF: 'dataset/factorTableF.xlsx'   
      
    # filepath_factorsF: 'D:/Data/factorFunda/dataset/wts_factors&returns_F.h5'

    # filepath_ratioF: 'output/ratio_factor_sec/perf_ratio_sec_F.xlsx'

    # #detail: 'F策略日收益序列'
    # filepath_cumretF: 'output/BigMomPVFF/BigMomPVFF_cumret.xlsx'
    
    # ## 输出相关文件
    # filepath_capitalPVF: 'position_trade/BigMomPVFPVF_capital.csv'
    
    # filepath_tradePosition: 'position_trade/WTS_PVF/'
    
    # filepath_templete: 'position_trade/CTA_BigMom.csv'
      
    